CALL insert_images('Lehetu kõlakoda', 'Lehetu', 4);
CALL insert_images('Varbola kõlakoda', 'Varbola', 4);
CALL insert_images('Kärla kõlakoda', 'Kärla', 4);
CALL insert_images('Kelvingi kõlakoda', 'Kelvingi', 3);
CALL insert_images('Kirna laululava', 'Kirna', 5);
CALL insert_images('Tolla külaplatsi lava', 'Tolla', 4);
CALL insert_images('Järlepa laululava', 'Järelpa', 2);
CALL insert_images('Prangli laululava', 'Prangli', 2);
CALL insert_images('Haimre laululava', 'Haimre', 3);
CALL insert_images('Märjamaa laululava', 'Märjamaa', 4);
CALL insert_images('Kõltsu mõisapargi laululava', 'Kõltsu', 4);
CALL insert_images('Kolga-Aabla laululava', 'Kolga-Aabla', 4);
CALL insert_images('Maidla külakeskuse laululava', 'Maidla', 4);
CALL insert_images('Kohatu jaanitule laululava', 'Kohatu', 4);
CALL insert_images('Jõgisoo Seltsimaja laululava', 'Jõgisoo', 3);
CALL insert_images('Lahu laululava', 'Lahu', 3);
CALL insert_images('Vaeküla kõlakoda', 'Vaeküla', 3);
CALL insert_images('Kihelkonna laululava', 'Kihelkonna', 4);
CALL insert_images('Taritu kõlakoda', 'Taritu', 4);
CALL insert_images('Tõhela laululava', 'Tõhela', 4);
CALL insert_images('Mustjala kõlakoda', 'Mustjala', 5);
CALL insert_images('Tudu laulu koda', 'Tudu', 4);
CALL insert_images('Turba kultuurimaja välilava', 'Turba', 4);
CALL insert_images('Aegviidu kõlakoda', 'Aegviidu', 3);
CALL insert_images('Naistevalla', 'Naistevalla', 2);
CALL insert_images('Oela laululava', 'Oela', 7);
CALL insert_images('Tõstamaa', 'Tõstamaa', 4);
CALL insert_images('Valtu vabaõhulava', 'Valtu', 4);
CALL insert_images('Hiiu kõlakoda', 'Hiiu', 3);
CALL insert_images('Aegviidu kõlakoda', 'Aegviidu', 3);
CALL insert_images('Keila väike laululava', 'Keila-väike', 2);
CALL insert_images('Keila suur laululava', 'Keila-suur', 4);
CALL insert_images('Kodila laululava', 'Kodila', 5);
CALL insert_images('Vana-Vigala laululava', 'Vana-Vigala', 5);